FROM rabbitmq:3-management

COPY rabbitmq.config /etc/rabbitmq/

RUN rabbitmq-plugins enable rabbitmq_web_stomp
RUN rabbitmq-plugins enable rabbitmq_tracing
RUN rabbitmq-plugins enable rabbitmq_mqtt
EXPOSE 4369 5671 5672 25672 15672 1883

CMD ["rabbitmq-server"]
